### ISSUE TITLE
CHAPTER 8 행동 디자인 패턴 - 3

### ISSUE THREAD

**Issue by audxo112** [BoostStudy/design-patterns#11]
### 8.7 반복자 패턴 (1)

이번 절에 제공된 Java 의 반복자를 기준으로 할 때, 다음 코드와 같이 컬렉션이 동시에 두 개의 반복자를 생성하는 경우, 반복자 중 하나가 remove() 메서드를 호출하여 컬렉션의 요소를 제거하고 난 상태에서 다른 반복자를 계속 사용할 수 있는지 생각해보자. 또한 다른 반복자에서 next() 함수를 호출한 결과는 무엇일지도 고민해보자.

### 8.8 반복자 패턴 (2)

8.8.3 절에 제공된 두 번째 설계 사상에서 삭제된 요소는 단순히 삭제되었다고 표시될 뿐이며, 반복자가 이 요소를 순회하지 않더라도 실제 배열에는 남아 있는 상태이기 때문에 불필요한 메모리 낭비가 발생하게 된다. 이 문제를 해결할 최적화 방법에는 어떤 것이 있는지 생각해보자.

### 8.9 비지터 패턴

1) 비지터 패턴은 객체와 동작을 분리하는데, 이것이 객체지향 프로그래밍의 캡슐화 특성을 위반하는 것인지 생각해보자.

2) 8.9.2 절의 예제 코드에서 SingleDispatchClass 클래스를 다음과 같이 변경하면서 다른 코드는 변경하지 않는다면 DemoMain 클래스의 실행 결과는 어떨지 생각해보자 

```java
public class SingleDispatchClass {
    public void polymorphismFunction(ParentClass p) {
        p.f()
    }
    public void overloadFunction(ParentClass p) {
        p.f()
    }
    public void overloadFunction(ChildClass c) {
        c.f()
    }
}
```

### 8.10 메멘토 패턴

백업은 아키텍처 설계 또는 제품 설계에서 일반적으로 사용된다. 예를 들어 웹 브라우저를 다시 시작할 때 이전에 열린 페이지를 복원하도록 선택할 수 있다.. 이 밖에 다른 응용방법에 대해 생각해보자

### 8.11 커맨드 패턴

이번 절에서 설계한 모바일 게임 백엔드 서버에서 단일 스레드 패턴을 채택한다면, 멀티코어 시스템에서 CPU 리소스 사용을 어떻게 최대화할 수 있을지 생각해보자.

### 8.12 인터프리터 패턴

경고 규칙 분석 예제의 표현식에서 ()를 지원하도록 코드를 리팩터링하는 방법을 생각해보자

### 8.13 중재자 패턴

EventBus 프레임워크를 기반으로 옵서버 패턴을 쉽게 구현할 수 있다. 그렇다면 EventBus 프레임워크를 사용하여 중재자 패턴을 구현할 수 있는지 생각해보자.

**Comment by audxo112** [comment]
### 8.7

modCount 가 달라졌기 때문에 iterator2 에서는 ConcurrentModificationException이 발생한다

### 8.8

Collection 에서 iterator() 를 호출할때 메모리를 정리한다 
데이터를 3종류의 List로 관리
1. add, delete timestamp 를 저장한 리스트
2. get/set 에서 index 로 바로 접근하기위한 실제 데이터 리스트
3. iterator() 함수 호출시 timestamp 와 데이터의 sync 를 맞추기위한 mapping List 

next 에서 modCount 를 이용해서 동일한 상태인지 인식한것처럼 iterator 호출 시점에 lastModCount 와 modCount를 비교하여 데이터 sync 여부를 결정

### 8.9

1. 동작을 분리하기위해서 객체의 내부 데이터에 접근할 필요가 생겨서 캡슐화를 위반하는 케이스가 나올 수 있을 것 같다 
개인적으로는 Factory 대신 Visitor 를 사용해야할 필요성을 느끼지 못하겠음  

2.
```
I am ChildClass`s f().
I am ChildClass`s f().
```

### 8.10

편집기능을 구현했을 때 마지막에 사용한 기능 리스트를 맨 앞에 노출해주는 편의성 기능 

### 8.11

Thread 를 단일쓰레드를 사용하는 이유는 Context Switching 에서 사용되는 메모리를 아끼기 위함이다 
즉, 여러 Thread 에서  동작을 해도 Context Switching 이 일어나지 않는 분리된 동작을 병렬로 처리하면 효율적으로 사용할 수 있을 것이라 생각이된다 
예를 들면, 특정 서버나 채널에 대한 동작만 처리하게 구현한다 

### 8.12

() 를 추가 하는 경우 우선순위가 바뀌기 때문에 가장 먼저 처리해줘야하는 Expression 으로 구현하면 될 것 같다

### 8.13

이벤트를 받을 때 마다 동기화된 데이터를 연결되어 있는 Client 로 전송하는 방식으로 구현할 수 있다.

**Comment by ldh019** [comment]
### 7. 반복자 패턴

보통 많은 언어들이 반복자를 기본으로 제공함

커서 패턴이라고도 부름

컬렉션을 정해진 순서대로 가져올 때 사용함

- 컬렉션 컨테이너와 순회 작업을 하는 반복자를 분리해서 단일 책임을 확보함

커서를 한 칸 뒤로 이동하는 동작을 구현할 때, 해당 아이템을 들고오게 할 수 도, 따로 아이템을 얻게 할 수 도 있음

순회 방식에는 3가지가 있음 - for, foreach, 반복자

복잡한 데이터 구조에서는 for나 foreach를 사용하면 실수가 생길 수 있기 때문에 반복자도 사용함

요소 추가나 삭제가 발생하면 커서의 위치가 달라져서 문제가 생김

문제를 해결하기 위해서 2가지 방법이 있음

- 순회 동안 추가와 삭제를 허용하지 않음
- 요소 추가/삭제 후 컬렉션에 오류를 보고함

### 생각해보기

modCount가 다르니까 ConcurrentModificationException이 던져질 것입니다!

### 8. 반복자 패턴(2)

스냅숏 기능을 지원하는 반복자

스냅숏 : 원본 컬렉션의 복사본, 원본에 변경이 일어나도 변하지 않음

~~여기 설명글이 이상해요 요소 3 삭제해놨다고 해놓고 코드에는 2를 삭제하는데…?~~

복사본을 만든다고는 하지만 사실 얕은 복사가 일어나서 메모리를 많이 잡아먹진 않음

### 생각해보기

순회가 끝난 리스트에 한해서 탐색을 또 하면 시간이 오래 걸리려나

아무튼 끝났을 때 시간 비교해서 삭제하면 좋을 것 같아요

### 8.9 비지터 패턴

하나 이상의 작업을 객체 집합에 적용하여 객체에서 작업을 분리할 수 있음

다시 말하면, 비즈니스 코드와 데이터 구조를 분리하여 작업과 데이터를 나눈다는 뜻

상속과 오버로딩을 사용하면 하위 클래스 타입에 맞게 알아서 잘 돌아감

상위 클래스 - 함수 스켈레톤만 생성

하위 여러 클래스 - 해당 함수에 오버로딩 해서 생성

작업을 수행할 다른 클래스 - 하위 클래스 각각에 대한 함수를 오버로딩으로 생성

이중 디스패치 : 객체의 런타임 타입에 따라 **실행할 객체의 메서드**를 결정, 메서드의 런타임 파라미터 타입에 따라 **객체에서 실행할 메서드**가 결정 되는 것

- 단일 디스패치 : 런타임 타입에 따라 **실행될 메서드**만 결정됨(어떤 객체인지는 컴파일 타임 타입에 의해 결정됨)

### 생각해보기

위반한다고 할 수 있음. 근데 이렇게 하지 않으면 내부 코드가 더 더러워질텐데…

어차피 어떤 유형을 처리해야 하는지 알아야 한다면 위반하는 게 더 낫다고 생각함

I am ChildClass’s f() 가 두 번 나오겠지?

### 8.10 메멘토 패턴

객체 내부 상태를 획득하고, 상태를 외부에 저장하고, 객체를 이전 상태로 복구할 수 있음

스냅숏 패턴이라고도 부름

백업에 비중이 커지면 메모리나 시간 문제가 생김

증분 백업과 전체 백업을 같이 사용하는 방법도 있음

### 생각해보기

뒤로가기 저장해놓는게 제일 대표적인거 아닐까요? 앞으로갔다 뒤로갔다 할 수 있으니까

웹브라우저랑 비슷한건데 맥북 껐다 킬때 윈도우 그대로 켜지게 하는거 그런거?

### 8.11 커맨드 패턴

함수를 객체로 캡슐화하는 것

명령의 전송과 실행이 분리되기 때문에 복잡한 작업을 수행할 수 있음

### 생각해보기

잘 모르겠는데…? CPU 리소스를 언제 쓴다는거야 메모리 작업이 훨씬 많은데 CPU 리소스를 왜..?

### 8.12 인터프리터 패턴

언어에 대한 규칙을 정의하고 해석하는 것을 만드는 패턴

새로운 규칙이 있으면 그걸 입력을 받고 이해해서 출력을 해주는 걸 만드는 거 같음

### 생각해보기

괄호 안에 있는 걸 먼저 해야하니까 맨 바깥에서 괄호를 먼저 처리하고 떼어 내도록 만들어야 할듯

### 8.13 중재자 패턴

객체 컬렉션 간의 상호 작용을 캡슐화하는 중재자 객체를 정의, 직접적인 상호 작용을 피하기 위해 중재자 객체에게 상호 작용을 위임함

### 생각해보기

가능할 것 같다. 비슷하게 중재자에게 등록과 같은 절차를 밟고 이벤트에 할당을 해주면 거기에 맞게 전달받고 전해주고 하면 되지 않을까?

**Comment by lee-ji-hoon** [comment]
### 8.7

<img width="679" alt="image" src="https://github.com/user-attachments/assets/ae091661-f518-4cc5-a8b5-1fb16209bb4c">

난 throw가 안날거 같았는데 왜 throw가 나는거지 🤔 `iterator1` 에 cursor를 움직인거지 `iterator2`를 움직인게 아닌데?.. 서로 다른 객체라서 상관 없어야하는거 아냐? 각각의 modCount를 들고 있을거고

### 8.8

`Soft Reference`로 구현하면 되지 않을까? `Soft Reference`의 경우 메모리가 부족하다면(OOM 직전) 수거를 해가기 때문에 gc를 직접 실행할 필요도 없을거 같은데 (물론 의도치 않게 데이터가 사라지는 경우가 존재할수도 있어서 애매할거 같기도 하다. 근데 GC를 직접 add, remove할때마다 호출하기도 애매할거 같네)

### 8.9

1. 

비지터 패턴을 사용하면, 비지터 객체가 객체의 내부 상태에 접근할 수 있도록 객체가 자신을 공개해야 할 때가 있는데,  이건 객체의 내부 상태를 외부에 노출하는 결과를 만들게 되니까 위반하는거 아닐까?

2.

```
I am ChildClass`s f().
I am ChildClass`s f().
```

### 8.10

백업하니까 바로 Git 부터 떠오르네 👀


### 8.11

로드 밸런서를 이용해서 요청을 여러 서버 인스턴스에 분산하고 각 서버 인스턴스는 단일 스레드로 동작하는데, 전체 시스템은 병렬 처리를 하게끔 하면 리소스 사용을 최대화 하는게 아닐까?

### 8.12

적다가 보니까 동훈이랑 똑같네 👀

### 8.13

EventBus를 갖고 있는 Mediator를 하나 만들어서 처리하면 깔끔할거 같네

**Comment by s00jinYang** [comment]
## 8.7
그거 modCount는 ArrayList가 들고있고 expectedModCount는 iterator가 들고있어서 그런듯

## 8.8
흠. 배열의 n%가 삭제된 요소가 되어버리면 새 배열에 삭제되지 않은 요소만 복사하고 구)배열은 버려버리기?

## 8.9
1. 책에서 나온 예제를 기준으로 ResourceFile은 Extractor, Compressor라는 외부에 존재하는 인터페이스를 알아야 함
Extractor, Compressor는 PdfFile, PptFile, WordFile의 인터페이스와 상태에 접근할 수 있음
뭐.. 위반하긴 하겠죠?

## 8.12
1. ExpressionInterpreter에서 괄호도 처리하도록 추가하거나, 괄호 연산을 처리하는 인터프리터를 만들기? 근데 다른 인터프리터로 만들면 순서를 보장할 수가 잇나? 그냥 ExpressionInterpreter에 로직추가하는게 깔끔할듯 로직은 후위표기식 검색 ㄱ
